"use client";

import { ActionIcon, Box, Group, Paper, Stack, Table, Text, TextInput } from "@mantine/core";
import { ArrowDown, ArrowLeft, ArrowUp, EyeOff, RotateCcw, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { AppButton } from "@/components/ui/app-components";
import { toast } from "@/components/ui/toast";
import type { VideoDetailRecord, VideoTagRecord } from "@/modules/video-library";
import { formatDuration } from "@/components/video-card";

export function VideoAdminDetailPanel({ video: initialVideo }: { video: VideoDetailRecord }) {
  const [video, setVideo] = useState(initialVideo);
  const [title, setTitle] = useState(initialVideo.displayTitle);
  const [episodes, setEpisodes] = useState(initialVideo.episodes);
  const [tags, setTags] = useState<VideoTagRecord[]>(initialVideo.tags);
  const [tagName, setTagName] = useState("");
  const [pending, setPending] = useState<string | null>(null);

  async function saveTitle() { setPending("title"); const response = await fetch(`/api/videos/${video.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayTitle: title }) }); const payload = await response.json(); if (!response.ok) toast.error(payload.error ?? "保存失败"); else { setVideo(payload.video); toast.success("标题已保存"); } setPending(null); }
  async function changeStatus(action: "hide" | "restore" | "soft_delete") { setPending(action); const response = await fetch(`/api/videos/${video.id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const payload = await response.json(); if (!response.ok) toast.error(payload.error ?? "操作失败"); else { setVideo((current) => ({ ...current, status: payload.status })); toast.success("状态已更新"); } setPending(null); }
  async function saveOrder() { setPending("order"); const response = await fetch(`/api/videos/${video.id}/episodes/order`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ episodeIds: episodes.map((episode) => episode.id) }) }); if (!response.ok) toast.error("保存集数顺序失败"); else toast.success("集数顺序已保存"); setPending(null); }
  async function addTag() { if (!tagName.trim()) return; setPending("tag"); const response = await fetch(`/api/videos/${video.id}/tags`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: tagName }) }); const payload = await response.json(); if (!response.ok) toast.error(payload.error ?? "添加标签失败"); else { setTags(payload.tags); setTagName(""); toast.success("标签已添加"); } setPending(null); }
  async function removeTag(tagId: string) { const response = await fetch(`/api/videos/${video.id}/tags`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tagId }) }); const payload = await response.json(); if (response.ok) setTags(payload.tags); }

  function move(index: number, delta: number) { const next = [...episodes]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setEpisodes(next.map((episode, sortOrder) => ({ ...episode, sortOrder }))); }

  return <Stack gap="lg"><Group><AppButton component={Link} href="/admin/videos" variant="subtle" leftSection={<ArrowLeft size={15} />}>返回视频管理</AppButton><Text component="h1" size="20px" fw={700}>{video.displayTitle}</Text></Group>
    <Paper p="md" style={{ border: "1px solid var(--mantine-color-pink-1)", borderRadius: 10, background: "white" }}><Text fw={700} mb="md">基本信息</Text><Group align="flex-end"><TextInput label="展示标题" value={title} onChange={(event) => setTitle(event.currentTarget.value)} style={{ flex: 1 }} /><AppButton loading={pending === "title"} leftSection={<Save size={15} />} onClick={() => void saveTitle()}>保存标题</AppButton></Group><Text size="xs" c="ink.5" mt="sm">来源标题：{video.fileTitle} · {video.videoRootName || "视频库"}</Text></Paper>
    <Paper p="md" style={{ border: "1px solid var(--mantine-color-pink-1)", borderRadius: 10, background: "white" }}><Group justify="space-between" mb="md"><Text fw={700}>集数顺序</Text><AppButton size="xs" loading={pending === "order"} onClick={() => void saveOrder()}>保存顺序</AppButton></Group><Table><Table.Thead><Table.Tr><Table.Th w={50}>#</Table.Th><Table.Th>集标题</Table.Th><Table.Th w={130}>时长</Table.Th><Table.Th w={90}>状态</Table.Th><Table.Th w={90}>操作</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{episodes.map((episode, index) => <Table.Tr key={episode.id}><Table.Td>{index + 1}</Table.Td><Table.Td><Text size="sm" fw={600}>{episode.title}</Text><Text size="xs" c="ink.5" style={{ wordBreak: "break-all" }}>{episode.relativePath}</Text></Table.Td><Table.Td>{formatDuration(episode.durationSeconds)}</Table.Td><Table.Td>{episode.isMissing ? <Text size="xs" c="red">缺文件</Text> : <Text size="xs" c="green">正常</Text>}</Table.Td><Table.Td><Group gap={3}><ActionIcon size="sm" variant="default" disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp size={13} /></ActionIcon><ActionIcon size="sm" variant="default" disabled={index === episodes.length - 1} onClick={() => move(index, 1)}><ArrowDown size={13} /></ActionIcon></Group></Table.Td></Table.Tr>)}</Table.Tbody></Table></Paper>
    <Paper p="md" style={{ border: "1px solid var(--mantine-color-pink-1)", borderRadius: 10, background: "white" }}><Text fw={700} mb="md">标签</Text><Group mb="md" gap="xs" wrap="wrap">{tags.map((tag) => <Box key={tag.id} component="span" style={{ display: "inline-flex", alignItems: "center", gap: 5, padding: "4px 8px", border: "1px solid var(--mantine-color-pink-2)", borderRadius: 7, color: "var(--mantine-color-pink-6)", fontSize: 12 }}>{tag.displayNameZh || tag.name}<button type="button" onClick={() => void removeTag(tag.id)} style={{ border: 0, background: "none", cursor: "pointer", color: "inherit" }}>×</button></Box>)}</Group><Group align="flex-end"><TextInput label="新增通用标签" placeholder="例如 action" value={tagName} onChange={(event) => setTagName(event.currentTarget.value)} onKeyDown={(event) => { if (event.key === "Enter") void addTag(); }} style={{ width: 260 }} /><AppButton loading={pending === "tag"} onClick={() => void addTag()}>添加</AppButton></Group><Text size="xs" c="ink.5" mt="sm">视频来源标签内部使用 general 命名空间，界面不显示命名空间。</Text></Paper>
    <Paper p="md" style={{ border: "1px solid rgba(217,58,78,0.3)", borderRadius: 10, background: "white" }}><Text fw={700} c="red" mb="md">状态维护</Text><Group><AppButton variant="outline" leftSection={<EyeOff size={15} />} disabled={video.status === "hidden" || video.status === "deleted"} loading={pending === "hide"} onClick={() => void changeStatus("hide")}>隐藏</AppButton><AppButton variant="outline" leftSection={<RotateCcw size={15} />} disabled={video.status === "readable"} loading={pending === "restore"} onClick={() => void changeStatus("restore")}>恢复</AppButton><AppButton color="red" variant="outline" leftSection={<Trash2 size={15} />} disabled={video.status === "deleted"} loading={pending === "soft_delete"} onClick={() => void changeStatus("soft_delete")}>软删除</AppButton></Group></Paper>
  </Stack>;
}
