import { DEFAULT_CACHE_SIZE_MB, DEFAULT_LISTEN_HOST } from "@/modules/core/config";

import type { RuntimeSettings, SettingDefinition } from "./types";

export const defaultRuntimeSettings: RuntimeSettings = {
  listenHost: DEFAULT_LISTEN_HOST,
  cacheDirectory: ".data/cache",
  cacheSizeMb: DEFAULT_CACHE_SIZE_MB,
  readerThumbnailTtlDays: 30,
  readerPreloadEnabled: true,
  readerPreloadAheadPages: 2,
  readerThumbnailSidebarDefault: true,
  readerImmersiveDefault: false,
  themeMode: "light",
  metadataImportToken: "",
  downloadDefaultTargetDirectory: "",
  openlistEnabled: false,
  openlistBaseUrl: "",
  openlistToken: "",
  openlistUsername: "",
  openlistPassword: "",
  openlistOfflineSavePath: "/115Open/Temp",
  openlistLibraryScanRoot: "/115Open/HENTAI/exhentai",
  aria2Enabled: false,
  aria2RpcUrl: "",
  aria2RpcToken: "",
  potplayerExecutablePath: "",
  pixivDownloaderDbPath: "",
  pixivDownloaderDownloadRoot: "",
  pixivDownloaderMangaRootId: "",
};

export const settingDefinitions = [
  {
    key: "listenHost",
    label: "监听地址",
    description: "默认只监听本机。开启局域网访问后，写 API 必须使用 token。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.listenHost,
  },
  {
    key: "cacheDirectory",
    label: "缓存目录",
    description: "用于压缩包文件列表、最近访问页面、封面和 reader 缩略图缓存。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.cacheDirectory,
  },
  {
    key: "cacheSizeMb",
    label: "缓存大小上限",
    description: "缓存清理同时使用大小上限和过期时间。",
    valueType: "number",
    defaultValue: defaultRuntimeSettings.cacheSizeMb,
  },
  {
    key: "readerThumbnailTtlDays",
    label: "Reader 缩略图过期天数",
    description: "缩略图按当前页和可视区域附近懒生成，命中缓存时立即显示。",
    valueType: "number",
    defaultValue: defaultRuntimeSettings.readerThumbnailTtlDays,
  },
  {
    key: "readerPreloadEnabled",
    label: "Reader 图片预加载",
    description: "阅读时预加载当前页附近的后续图片。",
    valueType: "boolean",
    defaultValue: defaultRuntimeSettings.readerPreloadEnabled,
  },
  {
    key: "readerPreloadAheadPages",
    label: "Reader 预加载页数",
    description: "阅读时向后预加载多少页。",
    valueType: "number",
    defaultValue: defaultRuntimeSettings.readerPreloadAheadPages,
  },
  {
    key: "readerThumbnailSidebarDefault",
    label: "默认显示缩略图侧栏",
    description: "桌面端打开 reader 时默认显示页面缩略图侧栏。",
    valueType: "boolean",
    defaultValue: defaultRuntimeSettings.readerThumbnailSidebarDefault,
  },
  {
    key: "readerImmersiveDefault",
    label: "默认沉浸阅读",
    description: "打开 reader 时默认隐藏顶部工具栏。",
    valueType: "boolean",
    defaultValue: defaultRuntimeSettings.readerImmersiveDefault,
  },
  {
    key: "themeMode",
    label: "主题模式",
    description: "MVP 固定浅色主题；深色主题需要完整 token 和对比度适配后再启用。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.themeMode,
  },
  {
    key: "metadataImportToken",
    label: "Metadata 导入令牌",
    description: "浏览器插件提交详情页 metadata 时必须携带的本地写入令牌。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.metadataImportToken,
  },
  {
    key: "downloadDefaultTargetDirectory",
    label: "默认下载目录",
    description: "下载任务未指定目标目录时使用的绝对路径。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.downloadDefaultTargetDirectory,
  },
  {
    key: "openlistEnabled",
    label: "启用 OpenList",
    description: "允许下载模块后续使用 OpenList provider。",
    valueType: "boolean",
    defaultValue: defaultRuntimeSettings.openlistEnabled,
  },
  {
    key: "openlistBaseUrl",
    label: "OpenList 服务地址",
    description: "OpenList API 的 http 或 https 地址。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.openlistBaseUrl,
  },
  {
    key: "openlistToken",
    label: "OpenList token",
    description: "OpenList provider 使用的本地访问令牌。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.openlistToken,
  },
  {
    key: "openlistUsername",
    label: "OpenList 用户名",
    description: "保存后可在 token 过期时自动重新登录。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.openlistUsername,
  },
  {
    key: "openlistPassword",
    label: "OpenList 密码",
    description: "保存后可在 token 过期时自动重新登录；仅存本地 SQLite。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.openlistPassword,
  },
  {
    key: "openlistOfflineSavePath",
    label: "OpenList 离线保存路径",
    description: "提交 115/OpenList 离线任务时的云端保存目录，例如 /115Open/Temp。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.openlistOfflineSavePath,
  },
  {
    key: "openlistLibraryScanRoot",
    label: "OpenList 云端库扫描路径",
    description: "10008 重复任务恢复与「重扫云端库」使用的扁平库根，例如 /115Open/HENTAI/exhentai。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.openlistLibraryScanRoot,
  },
  {
    key: "aria2Enabled",
    label: "启用 aria2",
    description: "启用 aria2 provider 用于磁链和 torrent 资源下载。",
    valueType: "boolean",
    defaultValue: defaultRuntimeSettings.aria2Enabled,
  },
  {
    key: "aria2RpcUrl",
    label: "aria2 RPC 地址",
    description: "aria2 JSON-RPC 端点地址，例如 http://127.0.0.1:6800/jsonrpc。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.aria2RpcUrl,
  },
  {
    key: "aria2RpcToken",
    label: "aria2 RPC 密钥",
    description: "aria2 RPC secret token（--rpc-secret），留空表示无密钥。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.aria2RpcToken,
  },
  {
    key: "potplayerExecutablePath",
    label: "PotPlayer 路径",
    description: "用于由本机服务启动 PotPlayer 的可执行文件绝对路径；也可使用浏览器 potplayer:// 协议。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.potplayerExecutablePath,
  },
  {
    key: "pixivDownloaderDbPath",
    label: "PixivDownloader 数据库路径",
    description: "PixivDownloader SQLite .db 文件的绝对路径，只读访问。Windows 安装示例：C:\\Program Files\\PixivDownload\\data\\pixiv_download.db。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.pixivDownloaderDbPath,
  },
  {
    key: "pixivDownloaderDownloadRoot",
    label: "PixivDownloader 下载根目录",
    description: "PixivDownloader 保存作品的根目录，用于解析 artworks.folder 中的 {0} 占位符。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.pixivDownloaderDownloadRoot,
  },
  {
    key: "pixivDownloaderMangaRootId",
    label: "PixivDownloader 对应漫画根目录",
    description: "PixivDownloader 下载内容对应的 MangaTest 漫画根目录，扫描并同步时会先扫描该根目录。",
    valueType: "string",
    defaultValue: defaultRuntimeSettings.pixivDownloaderMangaRootId,
  },
] satisfies Array<SettingDefinition<RuntimeSettings[keyof RuntimeSettings]>>;
